name: Pull transcripts (daily)

# Give the workflow permission to push compiled files back to the repo
permissions:
  contents: write

on:
  schedule:
    # 10:30 UTC is 6:30 AM Eastern during daylight time
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  build-transcripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category: [mainstream, insider, recruiting]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yt-dlp and ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python3 -m pip install --upgrade yt-dlp

      - name: Prepare folders
        run: |
          mkdir -p transcripts/${{ matrix.category }}

      - name: Fetch latest video IDs (past 24h)
        run: |
          : > ids_${{ matrix.category }}.txt
          while read -r ch; do
            [ -z "$ch" ] && continue
            # List uploads from last 24h and append IDs
            yt-dlp --flat-playlist --dateafter now-1day --get-id "$ch" >> ids_${{ matrix.category }}.txt || true
          done < channels_${{ matrix.category }}.txt
          sort -u ids_${{ matrix.category }}.txt -o ids_${{ matrix.category }}.txt

      - name: Download captions for each video
        run: |
          while read -r id; do
            [ -z "$id" ] && continue
            yt-dlp "https://www.youtube.com/watch?v=${id}" \
              --skip-download \
              --write-auto-sub --write-subs --sub-langs "en.*" \
              --sub-format "vtt" \
              -o "transcripts/${{ matrix.category }}/%(upload_date)s_%(channel)s_%(id)s.%(ext)s" || true
          done < ids_${{ matrix.category }}.txt

      - name: Convert VTT to plain text and stitch
        run: |
          OUTFILE="transcripts/${{ matrix.category | toJSON }}"
          OUTFILE=${OUTFILE//\"/}   # clean quotes from toJSON
          OUTFILE="${OUTFILE^^}"    # uppercase folder name in bash
          OUTMD="transcripts/${OUTFILE}_COMPILED.md"

          echo "# ${OUTFILE} transcripts (past 24h)" > "$OUTMD"
          echo "" >> "$OUTMD"

          shopt -s nullglob
          for f in transcripts/${{ matrix.category }}/*.vtt; do
            echo "## $(basename "$f")" >> "$OUTMD"
            # remove headers and timestamps, collapse blank lines
            sed -E '/WEBVTT|Kind:|Language:/d; s/^[0-9]{1,3}$//; s/^([0-9:.,-> ]+)$//; /^\s*$/d' "$f" >> "$OUTMD"
            echo "" >> "$OUTMD"
          done

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add transcripts/* || true
          git commit -m "Daily transcripts $(date -u +"%Y-%m-%d") for ${{ matrix.category }}" || echo "Nothing to commit"
          git push
